print('Hola, cual es tu nombre?')
nombre = input()
print('vale, cual es tu edad')
edad = input()
print('ok, para finalizar cual es tu estatura?')
estatura = input()
print('mi nombre es ' + nombre)
print('Tengo '+ edad + ' años')
print('mi estatura es de '+ estatura)
